### ISSUE TITLE
some contribution i guess

### ISSUE THREAD

**Issue by EdwardDali** [AllAboutAI-YT/easy-local-rag#8]
Hi,

I liked your code as it was simple for me to understand it. So I played a little bit with it an created some changes using AI generated code and some logic :) I dont know how to contribute as a branch to your code and you moved to version 1.2 already ....so the code is here if it makes any sense to you:
https://github.com/EdwardDali/e-rag
PS: the main thing where I got stuck is when trying to implement some advanced embedding techniques in order for the tool to be able to do chapter summaries.
some description on these techniqes is here (found on the internet): https://pub.towardsai.net/advanced-rag-techniques-an-illustrated-overview-04d193d8fec6

**Comment by AllAboutAI-YT** [comment]
Hello =)

Great job and i will take a look and see if i can use some of it! Keep it up and tnx :)

Kris
